version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quotesc
      POSTGRES_USER: app
      POSTGRES_PASSWORD: passme
    ports:
      - 5432:5432


