version: '3'

volumes:
  postgres_data:
    driver: local

networks:
  quotesc-net:
    driver: bridge

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quotesc
      POSTGRES_USER: app
      POSTGRES_PASSWORD: passme
    ports:
      - 5432:5432
    networks:
      - quotesc-net

  quotesc:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    networks:
      - quotesc-net
    ports:
      - 8080:8080
